squadra: main.o tennista.o item_tennista.o list.o utils.o squadra.o
	gcc tennista.o main.o item_tennista.o list.o utils.o squadra.o -o squadra
squadra.o:
	gcc -c squadra.c
list.o:
	gcc -c list.c
utils.o:
	gcc -c utils.c
item_tennista.o:
	gcc -c item_tennista.c
main.o:
	gcc -c main.c
tennista.o:
	gcc -c tennista.c
clean:
	rm -f main.o tennista.o item_tennista.o list.o utils.o squadra.o squadra
